### ISSUE TITLE
Access to training Data

### ISSUE THREAD

**Issue by mr-sarthakgupta** [grip-unina/ClipBased-SyntheticImageDetection#3]
In the paper, it is mentioned that one could generate the training data using captions from images. Would it be possible to provide the training data used to train the models. I'd like to try and improve upon this work.

Also, please let us know the procedure for collection of test data, specifically the images listed in synthwildx.csv

**Comment by davin11** [comment]
- Next weeK, I will provide the captions list of the training.

- The images of the synthwildx dataset were handmade collected. In particular, we looked for images on the social network using the name of the generator as a tag. We also checked that there were no tags from other generators in the image description.

**Comment by ydvaayan** [comment]
Please provide the above listed resources. Also could you tell which text to image generator was used to generate the synthetic images in the reference set ?

**Comment by davin11** [comment]
training data are at the page:
https://github.com/grip-unina/ClipBased-SyntheticImageDetection/tree/main/data/train_set
