### ISSUE TITLE
Stable Diffusion Test Images

### ISSUE THREAD

**Issue by tedious-turtle** [grip-unina/ClipBased-SyntheticImageDetection#5]
Hi,

I'm trying to recreate some test results from your paper: In Table 4 and Table 5, you show columns for Stable Diffusion and Stable Diffusion XL. However, I cannot figure out which are the test sets you used for those columns.

As part of Section 3, you initially state that "... we generated the images ourselves for ... Stable Diff. [63], ... using the pre-trained models available online". However, in Section 6, you also mention that you used the Synthbuster datasets for Stable Diffusion 1.4, Stable Diffusion 2.0, and Stable Diffusion XL for Table 6.

Could you specify which data exactly is used for the Stable Diffusion and Stable Diffusion XL columns in Table 4 and Table 5? (... and possibly provide the data if it is not the one from Synthbuster but data created by yourselves?)

**Comment by davin11** [comment]
Hi,

- for SDXL (Stable Diffusion XL), we used only the images of Synthbuster dataset.
- for Stable Diffusion, we used both images of Synthbuster dataset and images generated by us.

We are evaluating whether to share the test images generated by us, I will inform you soon.

**Comment by tedious-turtle** [comment]
Thanks a lot for your reply -- I'll stay tuned.
